project:
  type: website

website:
  title: "Yiman's Data Analytics Journey"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: inclass/inclass03/inclass03.qmd
          - text: "Hands-on Exercise 2"
            href: inclass/inclass03/inclass03.qmd
          - text: "Hands-on Exercise 3"
            href: inclass/inclass03/inclass03.qmd
            
      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: inclass/inclass03/inclass03.qmd
          - text: "In-class Exercise 2"
            href: inclass/inclass03/inclass03.qmd
          - text: "In-class Exercise 3"
            href: inclass/inclass03/inclass03.qmd
          - text: "In-class Exercise 4"
            href: inclass/inclass03/inclass03.qmd
          - text: "In-class Exercise 5"
            href: inclass/inclass05/inclass05.qmd
          - text: "In-class Exercise 6"
            href: inclass/inclass06/Hands-on_Ex06-VisTime.qmd
          - text: "In-class Exercise 7"
            href: inclass/inclass07/inclass07.qmd
          - text: "In-class Exercise 8"
            href: inclass/inclass08/untitled.qmd
            
      - text: "Take-home Exercises"
        menu: 
          - text: "Take-home Exercise 1"
            href: TAKEHOME/TAKEHOME01/takehome01.qmd
          - text: "Take-home Exercise 2"
            href: TAKEHOME/TAKEHOME02/takehome2.qmd
          - text: "Take-home Exercise 3"
            href: TAKEHOME/TAKEHOME03/TAKEHOME03.qmd
          - text: "Take-home Exercise 4"
            href: TAKEHOME/TAKEHOME04/TAKEHOME04.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


