project:
  type: website

website:
  title: "Yiman's Data Analytics Journey"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: inclass/inclass03/inclass03.qmd
          - text: "Hands-on Exercise 2"
            href: inclass/inclass03/inclass03.qmd
          - text: "Hands-on Exercise 3"
            href: inclass/inclass03/inclass03.qmd
            
      - text: "in-class Exercises"
        menu: 
          - text: "in-class Exercise 1"
            href: inclass/inclass03/inclass03.qmd
          - text: "in-class Exercise 2"
            href: inclass/inclass03/inclass03.qmd
          - text: "in-class Exercise 3"
            href: inclass/inclass03/inclass03.qmd
          - text: "in-class Exercise 4"
            href: inclass/inclass04/inclass03.qmd
          - text: "in-class Exercise 5"
            href: inclass/inclass05/inclass05.qmd
            
      - text: "Take-home Exercises"
        menu: 
          - text: "Take-home Exercise 1"
            href: TAKEHOME/TAKEHOME01/takehome01.qmd
          - text: "Take-home Exercise 2"
            href: TAKEHOME/TAKEHOME02/takehome2.qmd
          - text: "Take-home Exercise 3"
            href: TAKEHOME/TAKEHOME03/TAKEHOME03.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


