---
title: "inclass-ex-04"
author: "Chen Yiman"
date: 4 February 2023
date-modified: "r Sys.Date"
execute:
  eval: true
  echo: true
  warning: false
format: html
editor: visual
listing: 
  contents: posts
---

```{r}
pacman::p_load(tidyverse,patchwork,plotly,DT)
```

```{r}
data <- read_csv('data/Exam_data.csv')
```

```{r}
plot_ly(data = data, 
        x = ~ENGLISH, 
        y = ~MATHS, 
        color = ~RACE) #<<

```

```{r}
p <- ggplot(data = data,
            aes(x = MATHS,
                y= ENGLISH))+
  geom_point(dotsize = 1)+
  coord_cartesian(xlim = c(0,100),
                  ylim = c(0,100))
ggplotly
```

```{r}
pacman::p_load(readxl, performance,parameter,see)
```

### Importing Excel file: readxl methods

```{r}
car_release <- read_xls("data/ToyotaCorolla.xls", 
                       "data")
car_release
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + 
              Weight + Guarantee_Period, data = car_release)
model
```

### Model Diagnostic: checking for multicolinearity:

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

### Model Diagnostic: checking normality assumption

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + 
              Weight + Guarantee_Period, data = car_release)
```

```{r}
check_n <- check_normality(model1)
```

```{r}
plot(check_n)
```

## Visualizing the uncertainty of point estimates

```{r}
pacman::p_load(tidyverse, plotly, crosstalk, DT, ggdist, gganimate)
```

```{r}
exam <- read_csv("data/Exam_data.csv")

```

### Visualizing the uncertainty of point estimates: ggplot2 methods

```{r}
pacman::p_load(tidyverse, plotly, crosstalk, DT, ggdist, gganimate)
```

```{r}
exam <- read_csv("data/Exam_data.csv")
```

```{r}
my_sum <- exam %>%
  group_by(RACE) %>%
  summarise(
    n=n(),
    mean=mean(MATHS),
    sd=sd(MATHS)
    ) %>%
  mutate(se=sd/sqrt(n-1))
```

```{r}
knitr::kable(head(my_sum),format = 'html')
```

```{r}
ggplot(my_sum) +
  geom_errorbar(
    aes(x=RACE, 
        ymin=mean-se, 
        ymax=mean+se), 
    width=0.2, 
    colour="black", 
    alpha=0.9, 
    size=0.5) +
  geom_point(aes
           (x=RACE, 
            y=mean), 
           stat="identity", 
           color="red",
           size = 1.5,
           alpha=1) +
  ggtitle("Standard error of mean 
          maths score by rac")
```

\

```{r}
exam %>%
  ggplot(aes(x = RACE, 
             y = MATHS)) +
  stat_pointinterval() +   #<<
  labs(
    title = "Visualising confidence intervals of mean math score",
    subtitle = "Mean Point + Multiple-interval plot")

```

```{r}
exam %>%
  ggplot(aes(x = RACE, y = MATHS)) +
  stat_pointinterval(.width = 0.95,
  .point = median,
  .interval = qi) +
  labs(
    title = "Visualising confidence intervals of mean math score",
    subtitle = "Mean Point + Multiple-interval plot")
```

```{r}
exam %>%
  ggplot(aes(x = RACE, 
             y = MATHS)) +
  stat_gradientinterval(   
    fill = "skyblue",      
    show.legend = TRUE     
  ) +                        
  labs(
    title = "Visualising confidence intervals of mean math score",
    subtitle = "Gradient + interval plot")
```

```{r}
devtools::install_github("wilkelab/ungeviz")
```

```{r}
library(ungeviz)
```

```{r}
ggplot(data = exam, 
       (aes(x = factor(RACE), y = MATHS))) +
  geom_point(position = position_jitter(
    height = 0.3, width = 0.05), 
    size = 0.4, color = "#0072B2", alpha = 1/2) +
  geom_hpline(data = sampler(25, group = RACE), height = 0.6, color = "#D55E00") +
  theme_bw() + 
  # `.draw` is a generated column indicating the sample draw
  transition_states(.draw, 1, 3)
```

```{r}
pacman::p_load(tidyverse, FunnelPlotR, plotly, knitr)
```

```{r}
covid19 <- read_csv("data/COVID-19_DKI_Jakarta.csv") %>%
  mutate_if(is.character, as.factor)
view(covid19)
```

```{r}
funnel_plot(
  numerator = covid19$Positive,
  denominator = covid19$Death,
  group = covid19$`Sub-district`
)
```

```{r}
funnel_plot(
  numerator = covid19$Death,
  denominator =covid19$Positive,
  group = covid19$`Sub-district`,
  data_type = "PR",  #<<
  xrange = c(0,6500),#<<
  yrange = c(0,0.05) #<<
)
```
